# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
    - uses: actions/checkout@v1.6.1
    
    - name: Set up JDK 8
      uses: actions/setup-java@v1.6.1
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd xxl-conf-admin
        mvn clean package
