# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'v1.6.1'
    - run: |
        sed -i "" "s/\/data/data/g" xxl-conf-admin/src/main/resources/logback.xml
        sed -i "" "s/\/data/data/g" xxl-conf-admin/src/main/resources/application.properties
        sed -i "" "s/root_pwd/uu123123/g" xxl-conf-admin/src/main/resources/application.properties
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd xxl-conf-admin
        pwd
        mvn clean package
    - run: |
        pwd
        ls 
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: xxl-conf-admin/target/xxl-conf-admin-1.6.1.jar
        
